inc:
  # Blog Information
  title:        "Crystal Finley"
  subtitle:     "BA, RMT, RHN, Yoga & Meditation, Osteopathy student"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  
  # Company information
  company:      Crystal Finley
  url:          http://crystalfinley.github.io/
  ## Disabled for now
  #facebook:     crystalfinley
  #twitter:      crystalfinley
  #gplus:        '000000000000000000'
  #about_link:   https://crystalfinley.github.io/about/
  
  # Product Information
  #product_link: http://www.crystalfinely.com/
  tagline:      "Massage, Health & Wellness in Halifax"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false
  
  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false
    
  
 # Analytics     
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://crystalfinley.github.io
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: pygments

# Removed in v3.0
#  relative_permalinks: true

gems:
 - jekyll-paginate

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  enable_coderay: false
  hard_wrap: false
  footnote_nr: 1

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

sass:
    style: :compressed

